group: "exp1-decoder-arch"
seed: 0

lapo:
  inv_stage: 1
  latent_action_dim: 6 # Cheetah
  labeled_loss_coef: 0.001 # 0.001 ONLY FOR CHEETAH
  ires_hidden_dim: 128
  ires_n_blocks: 2
  ires_n_power_iter: 5
  ires_coeff: 0.8
  ires_inv_max_iter: 100
  ires_fd_coef: 1e-4
  ires_fd_every: 10
  cycle_loss_coef: 0
  cycle_loss_every: 100
  
  num_epochs: 10
  batch_size: 512
  labeled_batch_size: 128
  cosine_loss: False
  use_aug: True
  # use_aug: False # No need on vanilla, augmentation would just add noise
  future_obs_offset: 10
  # future_obs_offset: 1 # single-step IDM, multi-step is for distractors
  learning_rate: 0.0001
  weight_decay: 0.0
  warmup_epochs: 3
  act_head_dim: 1024
  act_head_dropout: 0.0
  obs_head_dim: 1024
  obs_head_dropout: 0.0
  encoder_scale: 6
  encoder_num_res_blocks: 2
  encoder_dropout: 0.0
  encoder_norm_out: False
  encoder_deep: False
  target_tau: 0.001
  target_update_every: 1
  frame_stack: 3
  # TODO: change to your data and action-labeled data path, eval is optional
  data_path: "/data2/laom/data/dcs/cheetah/cheetah-run-dcs-train-5000traj.hdf5"
  labeled_data_path: "/data2/laom/data/dcs/cheetah/cheetah-run-dcs-labeled-125traj.hdf5"
  eval_data_path: "/data2/laom/data/dcs/cheetah/cheetah-run-dcs-eval-labeled-50traj.hdf5"
  # hopper
  # data_path: "/data2/laom/data/dcs/hopper/hopper-hop/dcs/train-5000traj.hdf5"
  # labeled_data_path: "/data2/laom/data/dcs/hopper/hopper-hop-dcs-labeled-125traj.hdf5"
  # eval_data_path: "/data2/laom/data/dcs/hopper/hopper-hop-dcs-eval-labeled-50traj.hdf5"
  # walker
  # data_path: "/data2/laom/data/dcs/walker/walker-run/dcs/train-5000traj.hdf5"
  # labeled_data_path: "/data2/laom/data/dcs/walker/walker-run-dcs-labeled-125traj.hdf5"
  # eval_data_path: "/data2/laom/data/dcs/walker/walker-run-dcs-eval-labeled-50traj.hdf5"

bc:
  standardize_targets: True
  
  num_epochs: 10
  batch_size: 512
  learning_rate: 0.0001
  weight_decay: 0.0 
  warmup_epochs: 0
  encoder_scale: 32
  encoder_num_res_blocks: 2
  encoder_deep: False
  dropout: 0.0
  use_aug: False
  frame_stack: 3
  # TODO: change to your data and DAVIS path
  data_path: "/data2/laom/data/dcs/cheetah/cheetah-run-dcs-train-5000traj.hdf5"
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 5
  eval_seed: 0

decoder:
  total_updates: 2500
  batch_size: 512
  learning_rate: 0.0003
  weight_decay: 0.0
  warmup_epochs: 0
  hidden_dim: 256
  use_aug: False
  # TODO: change to your DAVIS path
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 25
  eval_seed: 0